config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#index'
  resources :homes, except: [:destroy, :update] do
    resources :messages, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
  belongs_to :user
  has_many :messages

  validates :name, presence: true, uniqueness: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :home
  has_one_attached :image

  validates :user_id, presence: true
  validates :home_id, presence: true
  validates :comment, presence: true, unless: :was_attached?

  def was_attached?
    self.image.attached?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :homes
  has_many :messages

  validates :name, presence: true, length: {maximum: 8 }
  validates :address, presence: true, uniqueness: true
  ADDRESS_REGEX = /\A@+[a-z\d]+\z/i.freeze
  validates_format_of :address, with: ADDRESS_REGEX, message: 'は@半角英数字のみで設定してください'
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'は半角英数字混合で設定してください'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth
  
  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :address])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :move_to_index, except: [:index, :show]

  def index
    @new_homes = Home.includes(:user).order("created_at DESC").limit(5)
    @new_comment_homes = Home.includes(:user).order("updated_at DESC").limit(5)
    @all_homes = Home.includes(:user).order("updated_at DESC")
  end

  def new
    @home = Home.new
  end

  def create
    @home = Home.new(home_params)
    if @home.save
      redirect_to home_path(@home.id)
    else
      render :new
    end
  end

  def show
    @home = Home.find(params[:id])
    @messages = @home.messages
    @message = Message.new
  end

  def search
    unless params[:keyword] == ""
      @keys = SearchHomesService.search(params[:keyword])
    else
      redirect_to root_path
    end
  end

  private

  def home_params
    params.require(:home).permit(:name).merge(user_id: current_user.id)
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = Message.new(message_params)
    if @message.save
      query = "UPDATE homes, messages SET homes.updated_at = messages.updated_at WHERE homes.id = #{@message.home.id} AND messages.id = #{@message.id}"
      ActiveRecord::Base.connection.execute(query)
      redirect_to home_path(@message.home)
    else
      @home = @message.home
      @messages = @home.messages
      render "homes/show"
    end
  end
  
  private
  def message_params
    params.require(:message).permit(:comment, :image).merge(user_id: current_user.id, home_id: params[:home_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    query = "SELECT * FROM homes WHERE user_id = #{(params[:id])} ORDER BY updated_at DESC"
    @user_homes = Home.find_by_sql(query)
    query = "SELECT h.id,h.name,h.user_id,h.created_at,h.updated_at FROM homes h JOIN messages m ON h.id = m.home_id WHERE m.user_id = #{(params[:id])} GROUP BY h.id ORDER BY updated_at DESC;"
    @user_message_homes = Home.find_by_sql(query)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.erb
<div class= 'all'>
  <%= render "shared/home_header" %>

  <div class='main'>
    掲示板サイト「Hooome🏠」へようこそ！🎉</br>
    <div class='caption'>
    🌟ピックアップ🌟
    </div>
    <div class='pick_up'>
      <div class='left'>
        <ul class= 'lists'> 新規掲示板</br>
          <% @new_homes.each do |home| %>
            <li class= "list">
              <%= link_to home.name, home_path(home.id), method: :get, class: 'list_name' %>
              </br>
              <span class="list_info">
                投稿者:
                <%= link_to home.user.name, user_path(home.user.id), class: "list_user"%>
              </span>
              <span class="list_info">
                投稿:
                <%= home.created_at %>
              </span>
            </li>
          <% end %>
        </ul>
      </div>
      <div class='right'>
        <ul class= 'lists'> 新規更新</br>
          <% @new_comment_homes.each do |home| %>
            <li class= "list">
              <%= link_to home.name, home_path(home.id), method: :get, class: 'list_name' %>
              </br>
              <span class="list_info">
                投稿者:
                <%= link_to home.user.name, user_path(home.user.id), class: "list_user"%>
              </span>
              <span class="list_info">
                更新:
                <%= home.updated_at %>
              </span>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class='caption'>
    🌟掲示板一覧🌟
    </div>
    <ul class= 'lists_index'>
      <% @all_homes.each do |home| %>
        <li class= "list">
          <%= link_to home.name, home_path(home.id), class: 'list_name' %>
          </br>
          <span class="list_info">
            投稿者:
            <%= link_to home.user.name, user_path(home.user.id), class: "list_user"%>
          </span>
          <span class="list_info">
            コメント数:
            <%= home.messages.length %>
          </span>
          <span class="list_info">
            投稿:
            <%= home.created_at %>
          </span>
          <span class="list_info">
            更新:
            <%= home.updated_at %>
          </span>
        </li>
      <% end %>
    </ul>
  </div>
  <%= render "shared/home_footer" %>
</div>

app/views/homes/new.html.erb
<div class= 'all'>
  <%= render "shared/home_header" %>

  <div class='main'>
    掲示板作成
    <%= form_with model: @home, class: 'user_form', local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
      <div class="field">
        <div>
          <%= f.label :name %>
        </div>
        <%= f.text_field :name, autofocus: true, placeholder: "40字以内でタイトルを入力してください", maxlength:"40"%>
      </div>

      <div class="actions">
        <%= f.submit "投稿する" %>
      </div>
    <% end %>
  </div>

  <%= render "shared/home_footer" %>
</div>

app/views/homes/search.html.erb
<div class= 'all'>
  <%= render "shared/home_header" %>

  <div class='main'>
    <% if params[:keyword].start_with?("@") %>
      <div class='caption'>
      ユーザー検索結果(<%= @keys.length %>件)
      </div>
      <div class= 'user_info'>
        <ul class= 'lists_index'>
          <% @keys.reverse_each do |user| %>
            <li class= "list">
              <%= link_to user.name, user_path(user.id), class: 'list_name' %>
              </br>
              <span class="list_info">
                address:
                <%= user.address %>
              </span>
            </li>
          <% end %>
        </ul>
      </div>
    <% else %>
      <div class='caption'>
      掲示板検索結果(<%= @keys.length %>件)
      </div>
      <div class= 'user_info'>
        <ul class= 'lists_index'>
          <% @keys.reverse_each do |home| %>
            <li class= "list">
              <%= link_to home.name, home_path(home.id), class: 'list_name' %>
              </br>
              <span class="list_info">
                コメント数:
                <%= home.messages.length %>
              </span>
              <span class="list_info">
                投稿:
                <%= home.created_at %>
              </span>
              <span class="list_info">
                更新:
                <%= home.updated_at %>
              </span>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>

  <%= render "shared/home_footer" %>
</div>

app/views/homes/show.html.erb
<div class= 'all'>
  <%= render "shared/home_header" %>

  <div class='main_show'>
    <div class='hoom_title'>
      🌟<%= @home.name %>🌟
      <span class="side_right">
        <span class="lists">
          投稿者:
          <%= link_to @home.user.name, user_path(@home.user.id), class: "list_user"%>
        </span>
      </span>
    </div>
    <% i = 0 %>
    <% @messages.each do |message| %>
      <% i += 1 %>
      <div class="comments">
        <div>
          <%= i %>.
        </div>
        <div>
          <%= simple_format(message.comment) %>
        </div>
      </div>
      <div class = "message-image">
        <%= image_tag message.image.variant(resize: '500x500') if message.image.attached? %>
      </div>
      <div class="comments_info">
        <%= link_to message.user.name, user_path(message.user.id), class: "list_user"%>
        <%= message.created_at %>
      </div>
    <% end %>
  </div>
  <%= render "shared/comment_footer" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hooome</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_comment_footer.html.erb
<header class='comment-footer'>
  <div class= "comment-form">
    <% if user_signed_in? %>
      <%= form_with(model: [@home, @message], local: true) do |form| %>
        <div class="form-area">
          <div>
            <%= form.text_area :comment, placeholder: "コメントを入力してください",maxlength:"100" , class: "input-area", id: "article_text", rows: "2" %>
          </div>
          <div>
            <label class="photo">
              <span>画像</span>
              <%= form.file_field :image, class: 'hidden' %>
            </label>
          </div>
        </div>

        <div class="count">
          <span id="char_num">0</span>/100文字
        </div>
        <%= form.submit "送信" ,class:"btn" %>
      <% end %>
    <% else %>
      </br>
      ログインしないと掲示板に参加できません。</br>
      参加希望の方は右上の「アカウント」から
      「ユーザー作成」または「ログイン」を行なってください.
    <% end %>
  </div>
</header>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_home_footer.html.erb
<header class='home-footer'>
  #法に触れる利用はご遠慮ください
</header>

app/views/shared/_home_header.html.erb
<header class='home-header'>
  <div class="heading">
    <%= link_to 'Hooome🏠', root_path, class: "title" %>
  </div>
  <div class= "search-form">
    <%= form_with(url: search_homes_path, local: true, method: :get) do |form| %>
      <%= form.text_field :keyword, placeholder: "掲示板、@user_address", class: "input-box" %>
      <%= form.submit "検索" ,class:"btn" %>
    <% end %>
  </div>
  <div class="menu">
    <% if user_signed_in? %>
      <span class="menu_text"><%= current_user.name %>
        <ul class="menu_list">
          <li><%= link_to "マイページ", user_path(current_user.id), class: "menu_lists" %></br></li>
          <li><%= link_to "掲示板作成", new_home_path, class: "menu_lists" %></br></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete ,  class: "menu_lists" %></br></li>
        </ul>
      </span>
    <% else %>
      <span class="menu_text"><%= "アカウント" %>
        <ul class="menu_list">
          <li><%= link_to "新規作成", new_user_registration_path, class: "menu_lists" %></br></li>
          <li><%= link_to "ログイン", new_user_session_path, class: "menu_lists" %></br></li>
        </ul>
      </span>
    <%end%>
  </div>
</header>

app/views/shared/_user_header.html.erb
<header class='home-header'>
  <div class="heading">
    <%= link_to 'Hooome🏠', root_path , class: "title" %>
  </div>
</header>

app/views/users/show.html.erb
<div class= 'all'>
  <%= render "shared/home_header" %>

  <div class='main'>
    <div class='caption'>
      <% if user_signed_in? && current_user.id == @user.id %>
        マイページ
      <% else %>
        <%= @user.name%>さんのマイページ
      <% end %>
    </div>
    <div class= 'user_info'>
      ユーザーアドレス:
      <%= @user.address%>
    </div>
    <div class='pick_up'>
      <div class='left'>
        <div class= 'user_info'>
          作成した掲示板
          <ul class= 'lists_index'>
            <% @user_homes.each do |home| %>
              <li class= "list">
                <%= link_to home.name, home_path(home.id), class: 'list_name' %>
                </br>
                <span class="list_info">
                  コメント数:
                  <%= home.messages.length %>
                </span>
                <span class="list_info">
                  更新:
                  <%= home.updated_at %>
                </span>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class='right'>
        <div class= 'user_info'>
          コメントした掲示板
          <ul class= 'lists_index'>
            <% @user_message_homes.each do |home| %>
              <li class= "list">
                <%= link_to home.name, home_path(home.id), class: 'list_name' %>
                </br>
                <span class="list_info">
                  コメント数:
                  <%= home.messages.length %>
                </span>
                <span class="list_info">
                  更新:
                  <%= home.updated_at %>
                </span>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <%= render "shared/home_footer" %>
</div>